/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cenfotec.componentes.control;

import com.cenfotec.componentes.dao.UsuarioDAO;
import com.cenfotec.componentes.model.Usuario;
import com.cenfotec.componentes.model.Persona;
import com.cenfotec.componentes.model.Rol;
import javax.swing.JOptionPane;
/**
 *compact source file does not have main method in the form of void main(Sting[] args)
 * @author moren
 */
public class ControlUsuarioPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ControlUsuarioPanel
     */
    private int usuarioIdActual = 0;
    private UsuarioDAO usuarioDAO = new UsuarioDAO();
    private boolean modoAgregar = false;

    public ControlUsuarioPanel() {
        initComponents();
        inicializarEstado();
    }

    private void inicializarEstado() {
        nombreTextBox.setEnabled(false);
        usuarioTextBox.setEnabled(false);
        rolTextBox.setEnabled(false);
        modoAgregar = false;
        agregarButton.setText("Agregar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        actualizarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        nombreTextBox = new javax.swing.JTextField();
        usuarioTextBox = new javax.swing.JTextField();
        rolTextBox = new javax.swing.JTextField();
        editarButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();
        buscarUsuarioTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        agregarButton = new javax.swing.JButton();

        jLabel1.setText("Control de Usuarios");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Rol:");

        actualizarButton.setText("Actualizar");
        actualizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarButtonMouseClicked(evt);
            }
        });
        actualizarButton.addActionListener(this::actualizarButtonActionPerformed);

        eliminarButton.setText("Eliminar");
        eliminarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarButtonMouseClicked(evt);
            }
        });
        eliminarButton.addActionListener(this::eliminarButtonActionPerformed);

        nombreTextBox.addActionListener(this::nombreTextBoxActionPerformed);

        editarButton.setText("Editar");
        editarButton.addActionListener(this::editarButtonActionPerformed);

        buscarButton.setText("Buscar usuario");
        buscarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarButtonMouseClicked(evt);
            }
        });
        buscarButton.addActionListener(this::buscarButtonActionPerformed);

        agregarButton.setText("Agregar");
        agregarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarButtonMouseClicked(evt);
            }
        });
        agregarButton.addActionListener(this::agregarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(actualizarButton)
                                    .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(34, 34, 34)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(usuarioTextBox)
                                            .addComponent(rolTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarUsuarioTextBox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarButton)
                            .addComponent(buscarUsuarioTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(usuarioTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rolTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(actualizarButton)
                            .addComponent(editarButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminarButton)
                            .addComponent(agregarButton))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        try {

            Persona persona = new Persona(nombreTextBox.getText());
            Rol rol = new Rol(rolTextBox.getText());

            Usuario usuario = new Usuario(
                    usuarioIdActual,
                    usuarioTextBox.getText(),
                    persona,
                    rol
            );

            usuarioDAO.actualizarUsuario(usuario);

            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente");

            inicializarEstado();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void nombreTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextBoxActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        nombreTextBox.setEnabled(true);
        usuarioTextBox.setEnabled(true);
        rolTextBox.setEnabled(true);
    }//GEN-LAST:event_editarButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        try {
            Usuario usuario = usuarioDAO.buscarUsuario(buscarUsuarioTextBox.getText());

            if (usuario != null) {
                usuarioIdActual = usuario.getIdUsuario();
                nombreTextBox.setText(usuario.getPersona().getNombre());
                usuarioTextBox.setText(usuario.getUsername());
                rolTextBox.setText(usuario.getRol().getNombreRol());
            } else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }

            inicializarEstado();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void buscarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonMouseClicked

    }//GEN-LAST:event_buscarButtonMouseClicked

    private void actualizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarButtonMouseClicked
        
    }//GEN-LAST:event_actualizarButtonMouseClicked

    private void eliminarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarButtonMouseClicked

    }//GEN-LAST:event_eliminarButtonMouseClicked

    private void agregarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtonMouseClicked

    }//GEN-LAST:event_agregarButtonMouseClicked

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        if (!modoAgregar) {
            modoAgregar = true;
            agregarButton.setText("Confirmar");

            nombreTextBox.setText("");
            usuarioTextBox.setText("");
            rolTextBox.setText("");

            nombreTextBox.setEnabled(true);
            usuarioTextBox.setEnabled(true);
            rolTextBox.setEnabled(true);
        } else {
            try {
                Persona persona = new Persona(nombreTextBox.getText());
                Rol rol = new Rol(rolTextBox.getText());

                Usuario usuario = new Usuario(
                        usuarioTextBox.getText(),
                        persona,
                        rol
                );

                usuarioDAO.agregarUsuario(usuario);
                JOptionPane.showMessageDialog(this, "Usuario agregado correctamente");

                modoAgregar = false;
                agregarButton.setText("Agregar");
                inicializarEstado();

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al agregar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        try {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar este usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);
            
            if (confirmacion == JOptionPane.YES_OPTION) {
                usuarioDAO.eliminarUsuario(usuarioIdActual);

                nombreTextBox.setText("");
                usuarioTextBox.setText("");
                rolTextBox.setText("");

                JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");
                inicializarEstado();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField buscarUsuarioTextBox;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreTextBox;
    private javax.swing.JTextField rolTextBox;
    private javax.swing.JTextField usuarioTextBox;
    // End of variables declaration//GEN-END:variables
}